---
title: "Noam's Workbook"
author: "Noam Benkler"
date: "March 28, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(psych)
library(ggplot2)
library(plyr)
library(tidyverse)
library(caret)
library(Metrics)
library(dplyr)
library(corrplot)
library(randomForest)
library(readr)
```

#loading data
```{r}

train_dockets <- read.csv("C:/Users/asus/Dropbox/MUDAC/MUDAC/raw_data/train_dockets.csv")
train_termination_motions<-read.csv("C:/Users/asus/Dropbox/MUDAC/MUDAC/raw_data/train_terminating_motions.csv")
train_other_motions<-read.csv("C:/Users/asus/Dropbox/MUDAC/MUDAC/raw_data/train_other_motions.csv",header=TRUE)
test_dockets<-read.csv("C:/Users/asus/Dropbox/MUDAC/MUDAC/raw_data/test_dockets.csv",header=TRUE)
test_termination_motions<-read.csv("C:/Users/asus/Dropbox/MUDAC/MUDAC/raw_data/test_terminating_motions.csv",header=TRUE)
test_other_motions<-read.csv("C:/Users/asus/Dropbox/MUDAC/MUDAC/raw_data/test_other_motions.csv",header=TRUE)
```

#Data manipulation
##Wrangling
```{r}

```


#Questions

#Q4
##a)


















